django/airline/airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls")),
]

django/airline/flights/urls.py
from django.urls import path
from . import views

app_name="flights"
urlpatterns = [
    path('', views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
    ]
    

django/airline/users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path('', views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

django/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo1/', include("demo1.urls")),
    path('demo2/', include("demo2.urls")),
    path('demo3/', include("demo3.urls"))
]

django/demo1/urls.py
from django.urls import path
from . import views

app_name="demo1"
urlpatterns = [
    path("", views.index, name="index"),
    path("hi", views.index2, name="index2"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david"),
    # path("<str:name>", views.greet, name="greet"),
    path("<str:name1>", views.greet1, name="greet1")
    ]

django/demo2/urls.py
from django.urls import path
from . import views

app_name="demo2"
urlpatterns = [
    path("", views.index, name="index"),
]

django/demo3/urls.py
from django.urls import path
from . import views

app_name="demo3"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

django/airline/flights/models.py
from django.db import models

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.CharField(max_length=64)
    destination = models.CharField(max_length=64)
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"
        

django/airline/users/models.py
from django.db import models

# Create your models here.

django/demo1/models.py
from django.db import models

# Create your models here.

django/demo2/models.py
from django.db import models

# Create your models here.

django/demo3/models.py
from django.db import models

# Create your models here.

django/airline/flights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Flight, Airport, Passenger

# Create your views here.

def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(id=flight_id)
    passengers = flight.passengers.all()
    non_passengers = Passenger.objects.exclude(flights=flight).all()
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers": passengers,
        "non_passengers": non_passengers
    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger_id = int(request.POST["passenger"])
        passenger = Passenger.objects.get(pk=passenger_id)
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flight", args=(flight.id,)))

django/airline/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid Credentials"
            })
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
                "message": "Logged Out"
            })
            

django/demo1/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world!")

def brian(request):
    return HttpResponse("Hello, Brian!")

def david(request):
    return HttpResponse("Hello, David!")

# def greet(request, name):
#     return HttpResponse(f"Hello, {name}!")

def greet1(request, name1):
    return HttpResponse(f"Hello; {name1.capitalize()}!")

def index2(request):
    return HttpResponse("<h1 style=\"color:blue\">Hello, world!</h1>")

django/demo2/views.py
import datetime
from django.shortcuts import render

def index(request):
    now = datetime.datetime.now()
    return render(request, "demo2/index.html", {
        "demo2": now.month == 1 and now.day == 1
    })

django/demo3/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

#third method
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

tasks = ["foo", "bar", "baz"]

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "demo3/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("demo3:index"))
        else:
            return render(request, "demo3/add.html", {
                "form": form
            })
    return render(request, "demo3/add.html", {
        "form": NewTaskForm()
    })

#second method
# def index(request):
#     return render(request, "demo3/index.html", {
#         "tasks": tasks
#     })

# def add(request):
#     if request.method == "POST":
#         form = NewTaskForm(request.POST)
#         if form.is_valid():
#             task = form.cleaned_data["task"]
#             tasks.append(task)
#             return HttpResponseRedirect(reverse("demo3:index"))
#         else:
#             return render(request, "demo3/add.html", {
#                 "form": form
#             })
#     return render(request, "demo3/add.html", {
#         "form": NewTaskForm()
#     })

#first method
# def index(request):
#     return render(request, "demo3/index.html", {
#         "tasks": tasks
#     })

# def add(request):
#     return render(request, "demo3/add.html")

django/airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }} minutes</li>
    </ul>
    <a href="{% url 'flights:index' %}">All Flights</a>
    <h2>Passengers:</h2>
<ul>
    {% for passenger in passengers %}
        <li>{{ passenger }}</li>
    {% empty %}
        <li>No Passengers.</li>
    {% endfor %}
</ul>

<h2>Add Passengers</h2>
<form action="{% url 'flights:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="passenger" id="">
        {% for passenger in non_passengers %}
            <option value="{{ passenger.id }}">{{ passenger }}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>

{% endblock %}

django/airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights:</h1>
    <ul>
        {% for flight in flights %}
            <li><a href="{% url 'flights:flight' flight.id %}">Flight {{ flight.id }}</a>: {{ flight.origin }} to {{ flight.destination }}</li>
        {% endfor %}
    </ul>
{% endblock %}

django/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Flights</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

django/airline/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Users</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

django/airline/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text", name="username", placeholder="Username">
        <input type="password", name="password", placeholder="Password">
        <input type="submit", value="Login">
    </form>
{% endblock %}

django/airline/users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:logout' %}">Log Out</a>
{% endblock %}

django/demo2/templates/demo2/index.html
{% load static %}
<link rel="stylesheet" href="{'styles.css' %}">

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year's?</title>
    </head>
    <body>
        {% if demo2 %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

django/demo3/templates/demo3/add.html
{% extends "demo3/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'demo3:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'demo3:index' %}">View Tasks</a>
{% endblock %}

django/demo3/templates/demo3/index.html
{% extends "demo3/layout.html" %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
{% endblock %}

django/demo3/templates/demo3/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>